### ISSUE TITLE
Python api example wrong

### ISSUE THREAD

**Issue by cathmonster** [solidfire/Python-CLI#2]
Hello,
I setup a wrapper for soldFire API and example given can't work and will not work as is ...
endpoint_info = {'mvip': 192.168.140.5, 'login': 'admin',
                     'password': 'SuperDooperPassword!', 'port': 443,
                     'url': 'https://192.168.140.5:443'}

dictionary is not correctly setup, mainly {'mvip': 192.168.140.5
as pi needs to be string, right!!

also I am not able with proper dictionary to get   sf_client.volumes as this binding does not exist in client ...

Is there another branch that should be picked up ...

**Comment by ArielCHoffman** [comment]
HI Cathmonster!

The CLI is not officially ready for release, but it will be soon. If you want to play around with it before the official 1.0 release, you can pull it from the develop branch. I just updated the help in the develop branch today. I set up the release branch so that I could get my ducks in a row before the official release, but I see it is confusing so I'll go ahead and remove the release0.0 branch to avoid further confusion.

Let me know if you have any troubles and feel free to follow the project to be updated when the actual release comes out!

Thank you,
Ariel
